#!/bin/bash
domain=$(sudo yunohost app setting seafile domain)
mysql_pwd=$(sudo cat /etc/yunohost/mysql)

sudo service seafile-server stop

sudo rm -rf /var/www/seafile
sudo rm -f /etc/nginx/conf.d/$domain.d/seafile.conf
sudo rm -f /etc/init.d/seafile-server
sudo rm -r /etc/yunohost/apps/seahack

# Remove databases
mysql -u root -p$mysql_pwd -e "DROP DATABASE ccnetdb ; DROP DATABASE seafiledb ; DROP DATABASE seahubdb ; DROP USER seafile@localhost ;"

# Remove the service
sudo yunohost service remove seafile-server

sudo yunohost app ssowatconf
