#!/bin/bash
domain=$(sudo yunohost app setting seafile domain)

cd /var/www/seafile/seafile-server-*
sudo ./seafile.sh stop
sudo ./seahub.sh stop

sudo rm -rf /var/www/seafile
sudo rm -f /etc/nginx/conf.d/$domain.d/seafile.conf
sudo rm -f /etc/init.d/seafile-server
sudo rm -r /etc/yunohost/apps/seahack

# Remove databases
mysql -u root -p$root_pwd -e "DROP DATABASE ccnetdb ; DROP DATABASE seafiledb ; DROP DATABASE seahubdb ; DROP USER seafile@localhost ;"

ccnet_port=$(sudo yunohost app setting seafile ccnet_port)
seafile_port=$(sudo yunohost app setting seafile seafile_port)

# Close ports
open_ports=$(sudo yunohost app setting seafile open_ports)
if [ "$open_ports" = "Yes" ];
then
  sudo yunohost firewall disallow $ccnet_port
  sudo yunohost firewall disallow $seafile_port
fi

sudo yunohost app ssowatconf
