#!/bin/bash
app=seafile

final_path=/var/www/seafile
seafile_data=$final_path/seafile-data
mysql_pwd=$(sudo cat /etc/yunohost/mysql)
current_dir=${PWD}

# Include version.sh
source $final_path/installed/version.sh

# Check system architecture
if [ -f /usr/bin/rpi-update ]; then
  env=pi
elif [ `getconf LONG_BIT` -eq 64 ]; then
  env=x86-64
elif [ `getconf LONG_BIT` -eq 32 ]; then
  env=i386
else
  echo "Error: Architecture not recognized"
  exit 1
fi

# RPI version is not up to date
if [ "$env" = "pi" ];
then
  seafile_version=4.2.2
else
  seafile_version=4.2.2
fi

if [ "$seafile_version" == "$current_version_full" ]; then
  echo "Info: No updates are available at the moment, if a new version of seafile is out we will port the update soon."
  exit;
else
  # Download seafile package
  if [ "$env" = "pi" ];
  then
    sudo wget -P ../sources/ 'https://github.com/haiwen/seafile-rpi/releases/download/v'$seafile_version'_'$env'/seafile-server_'$seafile_version'_'$env'.tar.gz'
  else
    sudo wget -P ../sources/ 'https://bintray.com/artifact/download/seafile-org/seafile/seafile-server_'$seafile_version'_'$env'.tar.gz'
  fi
  sudo mkdir -p $final_path/seafile-server-$seafile_version
  sudo tar xzf ../sources/'seafile-server_'$seafile_version'_'$env'.tar.gz'
  sudo mv seafile-server-$seafile_version/* $final_path/seafile-server-$seafile_version

  # Stop seafile server
  sudo /etc/init.d/seafile-server stop

  if [ "$current_version_main" == "4" ]; then
    if [ "$current_version_small" == "0" ]; then
      # Run update script
      sudo cp ../sources/upgrade_4.0_4.1.exp $final_path/seafile-server-$seafile_version/upgrade/upgrade_4.0_4.1.exp
      cd $final_path/seafile-server-$seafile_version
      sudo chmod +x ./upgrade/upgrade_4.0_4.1.exp
      sudo chmod +x ./upgrade/upgrade_4.0_4.1.sh
      sudo ./upgrade/upgrade_4.0_4.1.exp $mysql_pwd
      sudo rm ./upgrade/upgrade_4.0_4.1.exp
      cd $current_dir

      # Close ports if necessary
      open_ports=$(sudo yunohost app setting seafile open_ports)
      if [ "$open_ports" = "Yes" ];
      then
        sudo yunohost firewall disallow $ccnet_port
        sudo yunohost firewall disallow $seafile_port
        sudo yunohost app setting seafile open_ports -v "No"
      fi
    fi
    if [ "$env" != "pi" ]; then
      # Upgrade to 4.2.2
      sudo cp ../sources/upgrade_4.1_4.2.exp $final_path/seafile-server-$seafile_version/upgrade/upgrade_4.1_4.2.exp
      cd $final_path/seafile-server-$seafile_version
      sudo chmod +x ./upgrade/upgrade_4.1_4.2.exp
      sudo chmod +x ./upgrade/upgrade_4.1_4.2.sh
      sudo ./upgrade/upgrade_4.1_4.2.exp
      sudo rm ./upgrade/upgrade_4.1_4.2.exp
      cd $current_dir
      echo 'COMPRESS_URL = MEDIA_URL' | sudo tee -a $final_path/seahub_settings.py
      echo 'STATIC_URL = MEDIA_URL+"assets/"' | sudo tee -a $final_path/seahub_settings.py
    fi
  fi

  # Symlink for media
  sudo ln -s $final_path/seafile-server-$seafile_version/seahub/media/ $final_path/seafile-server-$seafile_version/seafile/media

  # Set permissions
  sudo chown -R www-data:www-data $final_path

  # Start seafile server
  sudo /etc/init.d/seafile-server start

  # Remove old version files
  sudo rm -f $final_path/seafile-server-$current_version_full

  # Update version script
  sudo rm $final_path/installed/version.sh
  if [ "$env" = "pi" ];
  then
    sudo cp ../sources/version_pi.sh $final_path/installed/version.sh
  else
    sudo cp ../sources/version.sh $final_path/installed/version.sh
  fi
  sudo chmod +x $final_path/installed/version.sh

  # Reload Nginx and regenerate SSOwat conf
  sudo service nginx reload
  sudo yunohost app ssowatconf
fi
